package projectEuler.exercices

import java.util.Date

object Problem29 {
  /*
  Problem 29 : Distinct powers
  Description :
      How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?

      result = 9183
      time used  = 300

  */
  def main(args: Array[String]): Unit = {

    val startTime = new Date().getTime
    val result = (2 to 100).flatMap(a =>
      (2 to 100).map(b => BigInt(a).pow(b))).distinct.length
    println("result = " + result)

    val endTime = new Date().getTime
    println("time used  = " + (endTime - startTime))
  }

}
