package projectEuler.exercices

object Problem29 {
  /*
  Problem 29 : Distinct powers
  Description :
      How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?
  */
  def main(args: Array[String]): Unit = {
    val result = (2 to 100).flatMap(a =>
      (2 to 100).map(b => BigInt(a).pow(b))).distinct.length
    println("result = " + result)

  }

}
